services:
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 djangowebsocket.asgi:application
    volumes:
      - .:/code
    ports:
     - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

